//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"	//manually added by the programmer

<<<<<<< HEAD
=======
#define 	GREEN_MASK 	0x08
#define 	RED_MASK 	0x02


//*****************************************************************************
//
//!
//! A very simple example that toggles the on-board blue LED using PinMux for 
//! port initialization and functions in Peripheral Driver Library for port access
//
>>>>>>> 4a350fb2b679053f29dc2c1b0fe047249fcdf037
//*****************************************************************************
 uint8_t LED_data;
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF1 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
    //
    // Enable pin PF3 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);
    //
    // Enable pin PF0 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
    //
    // Enable pin PF4 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);	
    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
<<<<<<< HEAD
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
=======
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
	  //
	  //
    // Enable pin PF3 for GPIOOutput
>>>>>>> 4a350fb2b679053f29dc2c1b0fe047249fcdf037
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
		
		//*************************************************************
		//	The code above is automatically generated by PinMux
		//  The code below should be manually added by the programmer
		//*************************************************************
		
		//Enable pull-up on PF1
		GPIO_PORTF_PUR_R |= 0x11; 
		
}

int main(void)
{
	
		//initialize the GPIO ports	
		PortFunctionInit();
	
    //
    // Loop forever.
    //
    while(1)
    {

			if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00)	//SW2 is pressed
			{
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00); //Turn Pin 3 off
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00); //Turn Pin 1 off
				
			}
<<<<<<< HEAD
			
			else if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00)//SW1 is pressed
			{
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00); //Turn Pin 1 off
        // Delay for a bit.
				SysCtlDelay(2000000);	
        // Toggle the LED.
        LED_data^=0x08;	//toggle green LED (PF3)
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, LED_data);
			}
			else
			{		
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00); //Turn Pin 3 off				
        // Delay for a bit.
				SysCtlDelay(2000000);	
        // Toggle the LED.
        LED_data^=0x02;	//toggle red LED (PF1)
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, LED_data);
			}
    }
=======
>>>>>>> 4a350fb2b679053f29dc2c1b0fe047249fcdf037
}
